services:
  # 1. El Servidor del Juego
  xonotic-server:
    build: 
      context: .
      dockerfile: Dockerfile.xonotic
    image: server:latest
    container_name: servidor_xonotic
    ports:
      - "26000:26000/udp"
    volumes:
      - ./data:/home/xonotic/.xonotic
    
    restart: unless-stopped

  # 2. El Analizador de Red (Zeek)
  zeek-monitor:
    build: 
        context: .
        dockerfile: Dockerfile.zeek
    image: zeek:latest
    container_name: zeek_xonotic_monitor
    # Obligamos a Zeek a usar la misma red que el servidor de Xonotic
    network_mode: "service:xonotic-server"
    # Damos permisos a Zeek para que pueda capturar paquetes de red
    cap_add:
      - NET_ADMIN
      - NET_RAW

    #normal, malicious_autocliker,flood_attack
    environment:
      - ETIQUETA=malicious_autocliker
    volumes:
      # Carpeta local donde guardaremos los logs de texto que genere Zeek
      - ./traffic_logs:/traffic_logs
    # Le decimos a Zeek que escuche la interfaz 'eth0' en tiempo real
    depends_on:
      - xonotic-server
    restart: unless-stopped
    